### ISSUE TITLE
Cannot compile for Qt6 when Qt5 development files are present

### ISSUE THREAD

**Issue by Jan200101** [SnowyMouse/sameboy-dx#1]
Since both
`find_package(Qt5 COMPONENTS Widgets)`
and
`find_package(Qt6 COMPONENTS Widgets)` are executed they end up defining the same set of targets which ends up causing trouble down the line

```
CMake Error at /usr/lib64/cmake/Qt6Core/Qt6CoreVersionlessTargets.cmake:37 (message):
  Some (but not all) targets in this export set were already defined.

  Targets Defined: Qt::Core

  Targets not yet defined: Qt::CorePrivate

Call Stack (most recent call first):
  /usr/lib64/cmake/Qt6Core/Qt6CoreConfig.cmake:63 (include)
  /usr/share/cmake/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  /usr/lib64/cmake/Qt6/QtPublicDependencyHelpers.cmake:14 (find_dependency)
  /usr/lib64/cmake/Qt6Widgets/Qt6WidgetsDependencies.cmake:91 (_qt_internal_find_dependencies)
  /usr/lib64/cmake/Qt6Widgets/Qt6WidgetsConfig.cmake:50 (include)
  /usr/lib64/cmake/Qt6/Qt6Config.cmake:187 (find_package)
  CMakeLists.txt:34 (find_package)
```

**Comment by SnowyMouse** [comment]
I think I'm going to change it to just compile for Qt6 unless you specifically ask for Qt5 with a cache variable.

**Comment by SnowyMouse** [comment]
It should no longer look for Qt5 unless you specifically ask for Qt5 support.

It also no longer can build both a Qt5 and Qt6 version at the same time, but this isn't really necessary anymore. I'm probably going to drop Qt5 in a later version.

This should fix your issue!

**Comment by Jan200101** [comment]
Does indeed fix the issue
